name: CI/CD

on:
  push:
    branches: [ main ]  # Trigger the workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gojoe:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/gojoe:latest
        # Repeat for other images if you have any
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rproxy:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rproxy:latest
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/search:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/search:latest
    - name: Install cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -o ProxyCommand='cloudflared access ssh --hostname %h' -i private_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
          cd ~
          docker compose pull
          docker compose up -d
        EOF
